language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2

before_install:
  - gem install bundler --version 1.6.1
  - bundle install

env:
  - DB=postgresql

before_script:
  - rake app:db:create
  - rake app:db:migrate
  - rake app:db:test:prepare

